src/Entity/Ad.php
<?php

namespace App\Entity;

use App\Repository\AdRepository;
use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use phpDocumentor\Reflection\Types\This;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=AdRepository::class)
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 *     fields={"title", "slug"},
 *  message="déjà pris"
 * )
 */
class Ad
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * init the slug
     *
     * @ORM\PrePersist
     * @ORM\PreUpdate
     *
     * @return void
     */
    public function initializeSlug(){
        if (empty($this->slug)){
            $slugify = Slugify::create();
            $this->slug = $slugify->slugify($this->title);
        }
    }

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="text")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $coverImage;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\OneToMany(targetEntity=Image::class, mappedBy="ad", orphanRemoval=true)
     * @Assert\Valid()
     */
    private $images;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="ads")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity=Booking::class, mappedBy="ad")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="ad", orphanRemoval=true)
     */
    private $comments;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->getTitle();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    /**
     * Retourne un tableau des jours occuper
     * @return array
     */
    public function getNotAvalibleDate(): array
    {
        $notAvailableDAys= [];

        foreach ($this->bookings as $booking){
            // calculer les jours qui se trouvent entre la date d'arrivée et de départ
            $result = range(
                $booking->getStartDate()->getTimestamp(),
                $booking->getEndTime()->getTimestamp(),
                24 * 60 * 60
            );
            $days = array_map(function ($dayTimestamp){
                return new \DateTime(date('Y-m-d',$dayTimestamp));
            }, $result);
            $notAvailableDAys = array_merge($notAvailableDAys, $days);
        }
        return $notAvailableDAys;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->coverImage;
    }

    public function setCoverImage(string $coverImage): self
    {
        $this->coverImage = $coverImage;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setAd($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getAd() === $this) {
                $image->setAd(null);
            }
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    /**
     * Permet de récuperle commentaire de l'ulisateur
     *
     * @param User $author
     * @return Comment|null
     */
    public function getCommentFromAuthor(User $author){
        foreach ($this->comments as $comment){
            if ($comment->getAuthor() === $author) return $comment;
        }
        return  null;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * Permet d'obtnir la moyenne globale des notes de l'annonce
     *
     * @return float|int
     */
    public function getAvgRattings(){

        $sum = array_reduce($this->comments->toArray(), function ($total, $comments){
            return $total + $comments->getRating();
        },0);

        if (count($this->comments) > 0 ) return $sum / count($this->comments);

        return 0;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setAd($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->removeElement($booking)) {
            // set the owning side to null (unless already changed)
            if ($booking->getAd() === $this) {
                $booking->setAd(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAd($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAd() === $this) {
                $comment->setAd(null);
            }
        }

        return $this;
    }


}

src/Entity/Booking.php
<?php

namespace App\Entity;

use App\Repository\BookingRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=BookingRepository::class)
 * @ORM\HasLifecycleCallbacks()
 */
class Booking
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $booker;

    /**
     * @ORM\ManyToOne(targetEntity=Ad::class, inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ad;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\GreaterThan("today", message="La date d'arriver dois être ulterieure à aurjoud'hui", groups={"front"})
     * @Assert\Type("DateTimeInterface",message="Attention, la date d'arrivée doit être au bon format !")
     */
    private $startDate;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\GreaterThan(propertyPath="startDate", message="la date de départ dois êtr superieure à celle de départ", groups={"front"})
     * @Assert\Type("DateTimeInterface", message="Attention, la date d'arrivée doit être au bon format !")
     */
    private $endTime;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createAt;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private  $comment;

    /**
     * Callback
     * @ORM\PrePersist
     *
     * @return void
     */
    public function prePersist(){
        if(empty($this->createAt)){
            $this->createAt = new \DateTime();
        }

        if (empty($this->amount)){
            //prix  x * nombre de jour
            dump($this->ad);
            $this->amount = $this->ad->getPrice() * $this->getDuration();
        }
    }

    public function isBookableDates(){
        // connaitre les dates réservers
            $notAvailableDays = $this->ad->getNotAvalibleDate();
        //comparer les dates choisie avec les dates impossibles
        $bookingDayes = $this->getDays();

        $formatDay = function ($day){
            return $day->format('Y-m-d');
        };

        // deux array pour une conversion en chaine de caracteres
        $days = array_map($formatDay, $bookingDayes);

        $notAvailable = array_map($formatDay, $notAvailableDays);

        foreach ($days as $day ){
            if(array_search($day, $notAvailable) !== false) return false;
        }
        return true;

    }

    /**
     * Retourne un tableau des journées de réservation
     *
     * @return array // dateTime
     */
    public function getDays(): array
    {
        $result = range (
            $this->startDate->getTimestamp(),
            $this->endTime->getTimestamp(),
            24 * 60 * 60
        );

        $days = array_map(function ($dayTimeStanp){
            return new \DateTime(date('Y-m-d', $dayTimeStanp));
        }, $result);

        return $days;
    }

    public function getDuration(){
        $diff = $this->endTime->diff($this->startDate);
        return $diff->days;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBooker(): ?User
    {
        return $this->booker;
    }

    public function setBooker(?User $booker): self
    {
        $this->booker = $booker;

        return $this;
    }

    public function getAd(): ?Ad
    {
        return $this->ad;
    }

    public function setAd(?Ad $ad): self
    {
        $this->ad = $ad;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndTime(): ?\DateTimeInterface
    {
        return $this->endTime;
    }

    public function setEndTime(\DateTimeInterface $endTime): self
    {
        $this->endTime = $endTime;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeInterface
    {
        return $this->createAt;
    }

    public function setCreateAt(\DateTimeInterface $createAt): self
    {
        $this->createAt = $createAt;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }
}

src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\Booking;
use App\Entity\Comment;
use App\Form\BookingFormType;
use App\Form\CommentType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class BookingController extends AbstractController
{
    /**
     * @Route("/ad/{slug}/book", name="booking_create", methods={"GET", "POST"})
     * @IsGranted("ROLE_USER", message="Vous n'est pas autorisé à être ici")
     */
    public function create(Ad $ad, Request $request, EntityManagerInterface $emi): Response
    {
        $booking = new Booking();
        $form = $this->createForm(BookingFormType::class, $booking);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){
            $booking->setBooker($this->getUser())->setAd($ad);
            // si les dates ne sont pas disponible, return error
            if (!$booking->isBookableDates()){
                $this->addFlash('warning', 'les dates que vous avez choisie sont déjà prises');
            }
            else{
                //sinon ok
                $emi->persist($booking);
                $emi->flush();
                return $this->redirectToRoute('booking_show', [
                    'id'=>$booking->getId(),
                    'withAlert' => true
                ]);
            }
        }
        return $this->render('booking/create.html.twig', [
            'form' => $form->createView(),
            'ad' => $ad
        ]);
    }

    /**
     *
     * @Route("booking/{id}", name="booking_show")
     * @param Booking $booking
     * @param Request $request
     * @param EntityManagerInterface $emi
     * @return Response
     */
    public function show(Booking $booking, Request $request, EntityManagerInterface $emi){

        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);
        if ( $form->isSubmitted() and $form->isValid())
        {
            $comment->setAd($booking->getAd());
            $comment->setAuthor($this->getUser());
            $emi->persist($comment);
            $emi->flush();
            $this->addFlash('success', 'Votre note et commentaire on bien été ajouter');
        }

        return $this->render('booking/show.html.twig',[
                'booking'=> $booking,
                'form'=> $form->createView()
            ]
        );
    }


}

templates/booking/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Faite votre booking !{% endblock %}
{% block stylesheets %}

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/vanillajs-datepicker@1.2.0/dist/css/datepicker-bs4.min.css">
    {{ parent() }}

{% endblock %}
{% block body %}
    <div class="container">
        <div id="priceDay" class="d-none">{{ ad.price }}</div>
        <div class="d-none" id="allDayUsed">
            {% for day in ad.notAvalibleDate %}
                {{ day.format('d/m/Y') }}
            {% endfor %}
        </div>
        <h1>Je book now</h1>
        {{ form_start(form) }}
        <div class="alert alert-light">
            <h2> commencer par nous dire quelles sont les dates qui vous intéressent !</h2>
            <div class="row">
                <div class="col">
                    {{ form_row(form.startDate) }}
                </div>
                <div class="col">
                    {{ form_row(form.endTime) }}
                </div>
            </div>
            <div class="col">
                <h2>Vous avez un commentaire</h2>
                {{ form_row(form.comment) }}
            </div>
            <div class="col">
                <h4><span id="amount">...</span>&euro;</h4>
                <span id="days">0</span> nuits(s) à {{ ad.price }} / nuit
            </div>
        </div>
        <button type="submit" class="btn-success btn">Réserver</button>
        {{ form_end(form)  }}
    </div>

{% endblock %}

    {% block javascripts %}
        {{ encore_entry_script_tags('dataCalendar') }}
        <script>

        </script>
    {% endblock %}

templates/booking/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello BookingController!{% endblock %}

{% block body %}


{% endblock %}

templates/booking/show.html.twig
{% extends 'base.html.twig' %}
{% block title %}
    réservation n°{{ booking.id }}
{% endblock %}

{% block body %}
    {% set hote = booking.ad.author %}

    <div class="container">
    <h1>Votre réservation (n°{{ booking.id }})</h1>
    {% if app.request.query.get('withAlert') %}
        <div class="alert-success alert">
            Votre réservation auprés de
            <strong>
                <a href="{{ path('user_show', {'slug': hote.slug}) }}">{{ hote.fullName }}</a>
            </strong>
            pour l'annonce
            <strong>
                <a href="{{ path('ads_show',{ 'slug':booking.ad.slug }) }}">{{ booking.ad.title }}</a>
            </strong>
        </div>
    {% endif %}
    <div class="row">
        <div class="col-6"><div class="alert-light alert">
                <h2>Détails</h2>
                <dl class="row">
                    <dt class="col-md-4">Numéro</dt>
                    <dt class="col-md-8">{{ booking.id }}</dt>
                    <dt class="col-md-4">Date arrivéé</dt>
                    <dt class="col-md-8">{{ booking.startDate |date('d/m/Y')}}</dt>
                    <dt class="col-md-4">Date de départ</dt>
                    <dt class="col-md-8">{{ booking.endTime |date('d/m/Y')}}</dt>
                    <dt class="col-md-4">Nombre de nuit :</dt>
                    <dt class="col-md-8">{{ booking.duration }} nuit</dt>
                    <dt class="col-md-4">Montant :</dt>
                    <dt class="col-md-8">{{ booking.amount }}€</dt>
                    <dt class="col-md-4">Commantaire :</dt>
                    <dt class="col-md-8">{{ booking.comment | default('Aucun') }}</dt>
                </dl>
                <hr>
                <h2 class="alert-heading">
                    votre hôte
                </h2>
                <div class="row mb-3">
                    <div class="col-3">
                        <img src="{{ hote.picture }}" alt="avatar de {{ hote.fullname }}" class="avatar avatar-medium">
                    </div>
                    <div class="col-9">
                        <h4><a href="{{ path('user_show',{'slug': hote.slug}) }}">{{ hote.fullName }}</a></h4>
                    </div>
                    <span class="badge badge-primary">{{ hote.ads|length }} annonces </span>
                </div>
            </div>
            {{ hote.description|raw }}
            <a href="{{ path('user_show',{'slug': hote.slug}) }}" {{ hote.fullName }} class="btn btn-primary"> plus d'information sur {{ hote.firstName }}</a>

            <div class="alert alert-light" id="comment">
                <h2 class="alert-heading">
                    votre avis compte !
                </h2>

                {% if date() > date(booking.endTime) %}
                    {% set comment = booking.ad.commentFromAuthor(app.user) %}
                        {% if comment is not null %}
                            <blockquote>
                                {{ comment.content }}
                            </blockquote>
                            <strong>Note</strong>
                            {% include 'partials/rating.html.twig' with {'rating': comment.rating} %}
                        {% else %}
                                {{ form_start(form) }}
                                    {{ form_widget(form) }}
                                <button type="submit" class="btn btn-success">
                                    Confirmer
                                </button>
                                {{ form_end(form) }}
                        {% endif %}
                    {% else %}
                        <p> Vous ne pouvez pas votre voyage ne sera pas complet</p>
                    {% endif %}
            </div>
        </div>



        <div class="col-6">
            <div class="alert alert-light">
                <h2 class="alert-heading">
                    votre hébergement
                </h2>
                <h4>
                    <a href="{{ path('ads_show',{'slug' : booking.ad.slug}) }}">{{ booking.ad.title }}</a>
                </h4>
                <img src="{{ booking.ad.coverImage }}" alt="{{ booking.ad.title }}" class="img-fluid">
                {{ booking.ad.content|raw }}
                <a href="{{ path('ads_show',{'slug':booking.ad.slug}) }}" class="btn btn-primary">Plus d'information</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}