src/Entity/Ad.php
<?php

namespace App\Entity;

use App\Repository\AdRepository;
use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use phpDocumentor\Reflection\Types\This;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=AdRepository::class)
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 *     fields={"title", "slug"},
 *  message="déjà pris"
 * )
 */
class Ad
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * init the slug
     *
     * @ORM\PrePersist
     * @ORM\PreUpdate
     *
     * @return void
     */
    public function initializeSlug(){
        if (empty($this->slug)){
            $slugify = Slugify::create();
            $this->slug = $slugify->slugify($this->title);
        }
    }

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="text")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $coverImage;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\OneToMany(targetEntity=Image::class, mappedBy="ad", orphanRemoval=true)
     * @Assert\Valid()
     */
    private $images;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="ads")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity=Booking::class, mappedBy="ad")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="ad", orphanRemoval=true)
     */
    private $comments;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->getTitle();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    /**
     * Retourne un tableau des jours occuper
     * @return array
     */
    public function getNotAvalibleDate(): array
    {
        $notAvailableDAys= [];

        foreach ($this->bookings as $booking){
            // calculer les jours qui se trouvent entre la date d'arrivée et de départ
            $result = range(
                $booking->getStartDate()->getTimestamp(),
                $booking->getEndTime()->getTimestamp(),
                24 * 60 * 60
            );
            $days = array_map(function ($dayTimestamp){
                return new \DateTime(date('Y-m-d',$dayTimestamp));
            }, $result);
            $notAvailableDAys = array_merge($notAvailableDAys, $days);
        }
        return $notAvailableDAys;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->coverImage;
    }

    public function setCoverImage(string $coverImage): self
    {
        $this->coverImage = $coverImage;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setAd($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getAd() === $this) {
                $image->setAd(null);
            }
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    /**
     * Permet de récuperle commentaire de l'ulisateur
     *
     * @param User $author
     * @return Comment|null
     */
    public function getCommentFromAuthor(User $author){
        foreach ($this->comments as $comment){
            if ($comment->getAuthor() === $author) return $comment;
        }
        return  null;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * Permet d'obtnir la moyenne globale des notes de l'annonce
     *
     * @return float|int
     */
    public function getAvgRattings(){

        $sum = array_reduce($this->comments->toArray(), function ($total, $comments){
            return $total + $comments->getRating();
        },0);

        if (count($this->comments) > 0 ) return $sum / count($this->comments);

        return 0;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setAd($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->removeElement($booking)) {
            // set the owning side to null (unless already changed)
            if ($booking->getAd() === $this) {
                $booking->setAd(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAd($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAd() === $this) {
                $comment->setAd(null);
            }
        }

        return $this;
    }


}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity (
 *  fields={"email"},
 *  message="un autre utilisateur s'est déjà inscrit avec cette addresse mail, merci de la modifier"
 * )
 * @method string getUserIdentifier()
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $picture;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $hash;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length (min=10, minMessage="Vptre introduction dois faire au moins de 10 caractères")
     */
    private $introduction;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(message="Veuillez renseigner un email valide !")
     */
    private $email;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length (max=500, maxMessage="votre description ne dois pas dépasser les 500 carctères !")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity=Ad::class, mappedBy="author", orphanRemoval=false)
     */
    private $ads;

    /**
     * @ORM\ManyToMany(targetEntity=Role::class, mappedBy="users", cascade={"persist"})
     */
    private $userRoles;

    /**
     * @ORM\OneToMany(targetEntity=Booking::class, mappedBy="booker")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="author", orphanRemoval=true)
     */
    private $comments;

    /**
     * init the slug
     *
     * @ORM\PrePersist
     * @ORM\PreUpdate
     *
     * @return void
     */
    public function initializeSlug(){
        if (empty($this->slug)){
            $slugify = Slugify::create();
            $this->slug = $slugify->slugify($this->firstName.' '.$this->lastName);
        }
    }


    public function __toString()
    {
        return $this->getFullName();
    }

    public function __construct()
    {
        $this->ads = new ArrayCollection();
        $this->userRoles = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Ad[]
     */
    public function getAds(): Collection
    {
        return $this->ads;
    }

    public function addAd(Ad $ad): self
    {
        if (!$this->ads->contains($ad)) {
            $this->ads[] = $ad;
            $ad->setAuthor($this);
        }

        return $this;
    }

    public function removeAd(Ad $ad): self
    {
        if ($this->ads->removeElement($ad)) {
            // set the owning side to null (unless already changed)
            if ($ad->getAuthor() === $this) {
                $ad->setAuthor(null);
            }
        }

        return $this;
    }

    public function getRoles()
    {
        $roles = $this->userRoles->map(function ($role){
           return $role->getTitle();
        })->toArray();
        $roles[] = 'ROLE_USER';
        return $roles;

    }

    public function getPassword()
    {
        return $this->getHash();
    }

    public function getSalt(){}

    public function eraseCredentials(){}

    public function getUsername()
    {
        return  $this->getEmail();
    }
    public function getFullName(){
        return"{$this->getFirstName()} {$this->lastName}";
    }

    /**
     * @return Collection|Role[]
     */
    public function getUserRoles(): Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->removeElement($userRole)) {
            $userRole->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setBooker($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->removeElement($booking)) {
            // set the owning side to null (unless already changed)
            if ($booking->getBooker() === $this) {
                $booking->setBooker(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }
}

src/Form/AdType.php
<?php

namespace App\Form;

use App\Entity\Ad;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AdType extends ApplicationType
{


    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title',
                TextType::class,
                $this->setLabelHolder('Titre','Taper un super titre bien attréyant'))
            ->add('slug',
                TextType::class,
                $this->setLabelHolder('Adresse web', 'Taper l\'adresse du site web (automatique'),
                ['required' => false])
            ->add('price',
                MoneyType::class,
                $this->setLabelHolder('Prix par nuit','Indiquer le prix que vous voulez pour une nuit.'))
            ->add('introduction',
                TextType::class,
                $this->setLabelHolder('Introdcution','Donnez une description global de votre appartement'))
            ->add('content',
                TextareaType::class,
                $this->setLabelHolder('Description','Dites nous tous.'))
            ->add('coverImage',
                UrlType::class,
                $this->setLabelHolder('URL de l\'image', 'donnez une adresse d\'image qui donne envie'))
            ->add('rooms',
                IntegerType::class,
                $this->setLabelHolder('Nombre', 'Nombre de chambre le logement.'))
            ->add('images',
                CollectionType::class,
            [
                'entry_type' => ImageType::class,
                'allow_add' =>true,
                'allow_delete'=> true
            ])
            ->add('save',SubmitType::class, ['label'=>'save'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Ad::class,
        ]);
    }
}

templates/ad/_ad.html.twig
        {% set url = path('ads_show',{'slug': ad.slug}) %}
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <div class="card-header text-center">
                        {{ ad.rooms}} chambre, <strong>{{ ad.price}}€/jours</strong>
                        <br>
                        {% if ad.comments |length > 0 %}
                            {% include 'partials/rating.html.twig' with {'rating' : ad.avgRattings} %}
                            {% else %}
                        <smal>Pas encore noté</smal>
                        {% endif %}
                    </div>
                    <img src="{{ ad.coverImage}}" alt="image de l'appartement"
                         style="height: 200px; width: 100%; display: block;">
                    <p class="card-text">{{ ad.introduction}}</p>
                    <a href="{{ url  }}" class="card-link">En savoir plus</a>
                    {% if app.user and app.user == ad.author %}
                        <a href="{{ path('edit_ads',{'slug':ad.slug}) }}" class="btn btn-secondary">Édité l'annonce</a>
                    {% endif %}
                </div>
            </div>
        </div>

templates/ad/create.html.twig
{% extends 'base.html.twig' %}
{% block title %}Créer une annonce{% endblock %}
{% form_theme form _self %}
{% block body %}
    <div class="container"><h1>créer un nouvelle annonce</h1>
    {{ form_start(form) }}
    {{ form_end(form)  }}
    </div>
{% endblock %}

{% block _ad_images_widget %}
    <p>Ici, vous pouvez ajouter vos propres images !</p>
    {{ form_widget(form) }}
    <input type="hidden" id="widgets-counter" value="0">
    <div class="form-group">
        <button class="btn btn-primary" id="add-image" type="button">
            Ajouter une image
        </button>
    </div>
{% endblock %}

{% block _ad_images_entry_widget %}
    <div class="form-group" id="block_{{ id }}">
        {{ form_errors(form) }}
        <div class="row">
            <div class="col-10">
                <div class="row">
                    <div>
                        {{ form_errors(form.url) }}
                    </div>
                    <div class="col">
                        {{ form_widget(form.url) }}
                    </div>
                    <div>
                        {{ form_errors(form.caption) }}
                    </div>
                    <div class="col">
                        {{ form_widget(form.caption) }}
                    </div>
                </div>
            </div>
            <div class="col-2">
                <button type="button" data-action="delete" data-target="#block_{{ id }}" class="btn btn-danger">X</button>
            </div>
        </div>
    </div>
{% endblock %}


{% block _ad_images_entry_row %}
    {{ form_widget(form) }}
{% endblock %}

{% block javascripts %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

    {{ encore_entry_script_tags('generateInput') }}
{% endblock %}

templates/ad/edit.html.twig
{% extends 'base.html.twig' %}
{% block title %}éditer une annonce{% endblock %}
{% form_theme form _self %}
{% block body %}
    <div class="container"><h1>edit une annonce</h1>
        {{ form_start(form) }}

        {{ form_end(form)  }}
    </div>
{% endblock %}


{% block _ad_images_widget %}
    <p>Ici, vous pouvez ajouter vos propres images !</p>
    {{ form_widget(form) }}
    <input type="hidden" id="widgets-counter" value="0">
    <div class="form-group">
        <button class="btn btn-primary" id="add-image" type="button">
            Ajouter une image
        </button>
    </div>
{% endblock %}

{% block _ad_images_entry_widget %}
    <div class="form-group" id="block_{{ id }}">
        <div class="row">
            <div class="col-10">
                <div class="row">
                    <div>
                        {{ form_errors(form.url) }}
                    </div>
                    <div class="col">
                        {{ form_widget(form.url) }}
                    </div>
                    <div>
                        {{ form_errors(form.caption) }}
                    </div>
                    <div class="col">
                        {{ form_widget(form.caption) }}
                    </div>
                </div>
            </div>
            <div class="col-2">
                <button type="button" data-action="delete" data-target="#block_{{ id }}" class="btn btn-danger">X</button>
            </div>
        </div>
    </div>
{% endblock %}


{% block _ad_images_entry_row %}
    {{ form_widget(form) }}
{% endblock %}

{% block javascripts %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

    {{ encore_entry_script_tags('generateInput') }}
{% endblock %}

templates/ad/index.html.twig
{% extends '/base.html.twig' %}

{% block title %}Nos annonces{% endblock %}

{% block body %}
    <div class="container">
        <h1 class="my-3">nos annonces <i class="fa-solid fa-star-half-stroke"></i></h1>
        <div class="row">
            {% for ad in allAds %}
                {% include 'ad/_ad.html.twig' %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/ad/show.html.twig
{% extends 'base.html.twig' %}
{% block title %}
{{ ad.title }}
{% endblock %}
{% block body %}
    <div class="ad-titlee" style="background-image: url({{ ad.coverImage }})">
        <div class="container" >
            <h1>{{ ad.title }}</h1>
            <p>{{ ad.introduction }}</p>
            <p class="h2">
                <strong>{{ ad.rooms }} chambres </strong> pour <strong>{{ ad.price }}€</strong>
                par nuit
            </p>
            <a href="{{ path('booking_create',{'slug': ad.slug}) }}" class="btn btn-primary">
                Réserver
            </a>
            {% if app.user and app.user == ad.author %}
                <a href="{{ path('edit_ads',{'slug':ad.slug}) }}" class="btn btn-secondary">Édité l'annonce</a>
                <a href="{{ path('delete_ad',{'slug':ad.slug}) }}" class="btn btn-danger"
                onclick="return confirm(`Êtes vous sur de vouloir supprimer l'annonce : {{ ad.title}} ?`)"
                >delete l'annonce</a>
            {% endif %}
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-8 mb-3">
                {{ ad.content | raw}}
                <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        {% for image in ad.images %}
                            <li data-target="#carouselExampleIndicators" data-slide-to="{{ loop.index0 }}"
                                {% if loop.first %}class="active"{% endif %}></li>
                        {% endfor %}

                    </ol>
                    <div class="carousel-inner">
                        {% for image in ad.images %}
                            <div class="carousel-item {% if loop.first %}active{% endif %}">
                                <img class="d-block w-100" src="{{ image.url }}" alt="First slide">
                            </div>
                            <div class="carousel-caption d-none d-md-block">
                                <h5>{{ ad.title }}</h5>
                                <p>{{ image.caption }}</p>
                            </div>
                        {% endfor %}
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>

            <hr>
            <h2>comment :</h2>
            {% if ad.comments %}
                <div class="alert alert-info">
                    <h4 class="alert-heading">
                        <div class="row align-item-center">
                            <div class="col">
                                Note globale donée par nos utilisateur
                                <small>Cette moyenne est calculer sur {{ ad.comments | length}} avis</small>
                            </div>
                            <div class="col">
                                {% include 'partials/rating.html.twig' with {'rating': ad.avgRattings}  %}
                            </div>
                        </div>
                    </h4>
                </div>
                {% for comment in ad.comments %}
                    <blockquote class="blockquote">
                        <p class="mb-2">
                            "{{ comment.content }}"
                        </p>
                        <footer class="blockquote-footer">de <cite title="Source Title">{{ comment.author.fullname()}} </cite> le {{ comment.createdAt |date("d-m-Y") }}</footer>
                    </blockquote>
                    <p> note donnée : <strong>{{ comment.rating }}</strong>
                        {% include 'partials/rating.html.twig' with {'rating' : comment.rating } %}
                    </p>


                {% endfor %}
            {% else %}
            <p>cette annonce n'a pas encore de commentaire</p>
            {%  endif %}

            <div class="col">
            {%  set a = ad.author %}
            <div class="row mb-3 align-items-center">
                <div class="col-3">
                    <a href="{{ path('user_show', {'slug' : a.slug}) }}">
                        <img src="{{ a.picture}}" class="avatar avatar-medium" alt="Avatar de Jaseph">
                    </a>
                </div>
                <div class="col">
                    <a href="{{ path('user_show', {'slug' : a.slug}) }}">
                        <h3>{{ a.fullName }}</h3>
                    </a>
                    <span class="badge  rounded-pill bg-light">Nombre d'annonce : {{ a.ads | length }}</span>
                </div>
            </div>
            <p>{{ a.description | raw }}</p>
                </div>
        </div>
    </div>



{% endblock %}